development:
  adapter: mysql2
  database: saa
  username: root
  password: root
  timeout: 1800
  host: localhost

test:
  adapter: mysql2
  database: saa
  username: root
  password: root
  timeout: 1800
  host: localhost

production:
  adapter: mysql2
  database: saa
  username: root
  password: root
  timeout: 1800
  host: localhost